"""
Write assets/examples3d/MANIFEST.{json,md}: one row per render, tying it to an experiment id,
the IR it was drawn from, where that IR came from, and the commit that introduced it.

    python scripts/make_manifest.py

Experiment ids:
    tasks/<level>/<task>/ir.json          ->  L1/a1-a12-100ul
    out/<doi>/exp<N>/protocol.json        ->  doi:10.1371/journal.pone.0246302#exp2

A task IR is labelled `pipeline` when it is byte-identical to a paper2protocol output
(protocol.json), otherwise `handwritten`.
"""

import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from paper2protocol.check import check  # noqa: E402
from paper2protocol.models import Protocol  # noqa: E402

OUT = ROOT / "assets/examples3d"


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True).stdout.strip()


def introduced(path):
    """(short commit id, author) of the commit that first added `path`; ('untracked', '') if none."""
    rows = git("log", "--diff-filter=A", "--format=%h|%an", "--", str(path.relative_to(ROOT))).splitlines()
    return tuple(rows[-1].split("|", 1)) if rows else ("untracked", "")


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def stem(path):
    parts = path.relative_to(ROOT).parts
    return "-".join(parts[1:-1]) if parts[0] == "tasks" else f"paper-{parts[1].replace('.', '_')}-{parts[2]}"


def doi_of(out_dir):
    return json.loads((out_dir / "paper.json").read_text())["doi"]


pipeline = {}  # sha256 -> (doi, exp, path)
for p in sorted(ROOT.glob("out/*/exp*/protocol.json")):
    pipeline[sha(p)] = (doi_of(p.parent.parent), p.parent.name, p)

rows = []
for ir in sorted(ROOT.glob("tasks/**/ir.json")) + sorted(ROOT.glob("out/*/exp*/protocol.json")):
    name = stem(ir)
    if not (OUT / f"{name}.mp4").exists():
        continue
    proto = Protocol.model_validate_json(ir.read_text())
    rel = ir.relative_to(ROOT)
    if rel.parts[0] == "tasks":
        exp_id, src = "/".join(rel.parts[1:-1]), "handwritten"
        if sha(ir) in pipeline:
            doi, exp, srcpath = pipeline[sha(ir)]
            src = f"pipeline: doi:{doi}#{exp}"
            tracked = bool(git("ls-files", str(srcpath.relative_to(ROOT))))
            src += "" if tracked else " (source protocol.json untracked)"
    else:
        doi = doi_of(ir.parent.parent)
        exp_id, src = f"doi:{doi}#{ir.parent.name}", "pipeline"
    commit, author = introduced(ir)
    issues = check(proto)
    rows.append(dict(
        render=name, experiment_id=exp_id, ir=str(rel), ir_source=src, introduced_by=commit, author=author,
        title=proto.title, steps=len(proto.steps), containers=len(proto.containers),
        check_errors=sum(i.severity == "error" for i in issues),
        files=[f"{name}.mp4", f"{name}.gif", f"{name}_frames.png"],
    ))

for f in sorted(OUT.glob("*NO-LIFT*.mp4")):
    base = f.stem.replace("-NO-LIFT-collision", "")
    rows.append(dict(render=f.stem, experiment_id=f"{base} (variant)", ir=f"see {base}", ir_source="same IR, --no-lift",
                     introduced_by=introduced(f)[0], author=introduced(f)[1],
                     title="Forced collision demo: head drives at work height", steps=0, containers=0, check_errors=0,
                     files=[f.name, f.stem + ".gif", f.stem + "_frames.png"]))

(OUT / "MANIFEST.json").write_text(json.dumps(rows, indent=1, ensure_ascii=False) + "\n")
lines = ["# 3D render manifest", "",
         "Generated by `scripts/make_manifest.py`. `introduced_by` = commit that first added the IR.", "",
         "| Render | Experiment id | IR | IR source | Introduced by | Steps | Containers | Checker errors |",
         "|---|---|---|---|---|---:|---:|---:|"]
for r in rows:
    lines.append(f"| `{r['render']}` | `{r['experiment_id']}` | `{r['ir']}` | {r['ir_source']} | "
                 f"`{r['introduced_by']}` {r['author']} | {r['steps']} | {r['containers']} | {r['check_errors']} |")
(OUT / "MANIFEST.md").write_text("\n".join(lines) + "\n")
print(f"{len(rows)} renders -> {OUT.relative_to(ROOT)}/MANIFEST.json, MANIFEST.md")
