"""Write docs/task-sources.md: for every task, its plain-English instruction, the reference .py, and the paper's PDF.

    python scripts/task_sources.py [--check]      # --check fails if the committed file is stale

Everything comes from the repo: tasks/<task>/task.toml [[source]] -> sources/<slug>/record.json (PDF URL, licence,
code URLs). The only hand-written part is REF: which script is the reference for a task, because a repository
can hold dozens.
"""
import json
import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs/task-sources.md"
# task -> (vendored script or None, why not / note)
REF = {
    "opentrons-rna-extraction": ("sources/hulp-rna-extraction/code/viral_rna_extraction_protocol.py", "the oracle in `harbor/solution/` is this script, re-saved"),
    "colony-pcr-screening": ("sources/slowpoke/code/Colony_PCR/colony_PCR_workflow_OT2.py", "the task is inspired by it; its numbers differ"),
    "golden-gate-assembly": (None, "AssemblyTron generates protocols; not vendored (102 .py files)"),
    "ecoli-heat-shock-transformation": (None, "APEX is AGPL-3.0: cannot be vendored"),
    "ampure-bead-cleanup": (None, "no supported source: the claimed repo has no AMPure step"),
    "split-200ul-two-wells": ("tasks/split-200ul-two-wells/private/solution/protocol.py", "handwritten oracle (private, never published)"),
    "a1-a12-100ul": (None, "handwritten, no reference script; checked by spec_check fixtures"),
}


def link(text, target):
    return f"[{text}](../{target})"


def render() -> str:
    rows = []
    for t in sorted((ROOT / "tasks").iterdir()):
        meta = tomllib.loads((t / "task.toml").read_text())
        nl = link("instruction.md", f"tasks/{t.name}/public/instruction.md")
        srcs = meta.get("source", [])
        first = srcs[0] if srcs else None
        if first and first.get("experiment", "").startswith("exp") and meta["metadata"]["source"] == "paper2protocol":
            nl += " · " + link("protocol.txt", f"sources/{first['slug']}/pipeline/{first['experiment']}/protocol.txt")
        ref_path, note = REF[t.name]
        pdfs, papers, upstream = [], [], []
        for s in srcs:
            rec = json.loads((ROOT / f"sources/{s['slug']}/record.json").read_text())
            pdf = rec.get("pdf", {})
            if pdf.get("url"):
                ok = "" if pdf.get("redistributable") == "yes" else " (not redistributable)"
                pdfs.append(f"[{s['slug']}]({pdf['url']}){ok}")
            if rec.get("doi_primary"):
                papers.append(f"[{rec['doi_primary']}](https://doi.org/{rec['doi_primary']})")
            upstream += [f"[{c['repo']}]({c['url']})" for c in rec.get("code", []) if c.get("repo") and c["url"].startswith("https://github.com")][:1]
        ref = " · ".join(([link(pathlib.Path(ref_path).name, ref_path)] if ref_path else []) + list(dict.fromkeys(upstream))) or "none"
        ref += f"<br>{note}"
        rel = "; ".join(f"{s['slug']}{'#' + s['experiment'] if s.get('experiment') else ''}: {s['relation'].split(' (')[0].split(';')[0]}" for s in srcs) or "handwritten"
        rows.append(f"| `{t.name}` | {nl} | {ref} | {'<br>'.join(dict.fromkeys(pdfs)) or 'none'} | {rel} |")
    return ("# Where each task comes from\n\nGenerated by `scripts/task_sources.py` from each task's `task.toml` `[[source]]` and "
            "`sources/<slug>/record.json`. PDFs are linked, never stored in the repo.\n\n"
            "| Task | Plain-English instruction (NL) | Reference script | Original paper PDF | Relation |\n|---|---|---|---|---|\n"
            + "\n".join(rows) + "\n")


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else "docs/task-sources.md is stale: run scripts/task_sources.py")
    OUT.write_text(text)
    print(text)
